name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: rathdrumcfr_test
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo
          coverage: pcov

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Copy Env File
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile assets
        run: npm run build

      - name: Execute tests
        run: php artisan test --coverage
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

  deploy:
    runs-on: ubuntu-22.04
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        uses: Glennmen/ploi-deploy-action@v1.2.0
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
